In [2]:
import qiime2, biom, pandas as pd
pd.options.mode.chained_assignment = None

In [3]:
fungi_decon = pd.read_csv('data/count_data_fungi_decontaminated_HMS_1986samples.tsv', sep='\t', header=0)
fungi_decon.head()

,sampleid,G000001985,G000002515,G000002525,G000002545,G000002655,G000002715,G000002855,G000002945,G000003125,...,G009193645,G010015585,G010093625,G010724455,G011692745,G900007375,G900067095,G900074925,G900079805,G000277815
0,13722.58cfa82fe4b0c9d6adf6b62c,0,0,0,0,1,0,0,0,0,...,1,0,0,0,0,0,0,4,0,0
1,13722.58cfa82fe4b0c9d6adf6b5e0,0,0,0,0,0,0,0,0,0,...,1,0,1,0,0,0,0,2,0,0
2,13722.58cfa82ee4b0c9d6adf6af8e,1,0,0,0,0,0,0,0,0,...,5,0,0,0,0,0,0,977,0,0
3,13722.58cfa82ee4b0c9d6adf6af20,0,0,0,0,2,2,0,0,0,...,5,0,0,0,0,0,0,182,0,0
4,13722.58cfa82fe4b0c9d6adf6b669,0,0,0,0,1,1,0,0,0,...,2,0,0,0,0,0,0,6,0,0

In [4]:
fungi_high = pd.read_csv("data/count_data_fungi_high_coverage_HMS_1986samples.tsv",sep='\t',header= 0)
fungi_high.head()

,sampleid,G000002515,G000002545,G000003855,G000006335,G000006445,G000026945,G000091025,G000146045,G000149425,...,G001298625,G001417885,G001642055,G001661405,G002079055,G002775015,G003290485,G004154835,G004353045,G900007375
0,13722.58cfa82fe4b0c9d6adf6b62c,0,0,2,0,0,0,0,0,0,...,0,0,0,0,0,0,2,0,4,0
1,13722.58cfa82fe4b0c9d6adf6b5e0,0,0,0,0,2,0,0,0,0,...,0,0,0,0,0,0,2,0,8,0
2,13722.58cfa82ee4b0c9d6adf6af8e,0,0,3,0,0,0,0,0,0,...,0,0,0,0,0,2,5,0,11,0
3,13722.58cfa82ee4b0c9d6adf6af20,0,0,3,0,0,0,0,0,0,...,0,0,0,0,0,0,3,1,1,0
4,13722.58cfa82fe4b0c9d6adf6b669,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,1,1,2,0

In [5]:
fungi_intersect = pd.read_csv("data/count_data_fungi_WIS_intersect_HMS_1986samples.tsv",sep="\t",header=0)
fungi_intersect.head()

,sampleid,Candida_glabrata,Candida_tropicalis,Debaryomyces_hansenii,Schizophyllum_commune,Saccharomyces_cerevisiae,Fusarium_oxysporum,Pyrenophora_tritici-repentis,Malassezia_globosa,Candida_albicans,...,Pneumocystis_jirovecii,Alternaria_alternata,Wickerhamomyces_anomalus,Hyphopichia_burtonii,Cyberlindnera_jadinii,Tilletiopsis_washingtonensis,Malassezia_restricta,Byssochlamys_spectabilis,Sporisorium_graminicola,Ramularia_collo-cygni
0,13722.58cfa82fe4b0c9d6adf6b62c,0,0,0,0,0,0,0,12517,0,...,0,0,0,0,0,1,2,0,0,4
1,13722.58cfa82fe4b0c9d6adf6b5e0,0,0,2,0,0,4,0,13251,0,...,0,0,0,0,0,0,2,1,0,2
2,13722.58cfa82ee4b0c9d6adf6af8e,0,0,0,0,0,0,0,12764,1,...,0,0,0,0,0,0,5,0,0,977
3,13722.58cfa82ee4b0c9d6adf6af20,0,0,0,0,0,0,0,17941,0,...,0,0,0,0,0,0,3,2,1,182
4,13722.58cfa82fe4b0c9d6adf6b669,0,0,0,0,0,0,0,20467,1,...,0,0,0,0,0,0,1,0,0,6

In [6]:
fungi_metadata = pd.read_csv("data/metadata_fungi_HMS_1986samples.tsv",sep="\t",header=0)
fungi_metadata.head()

,sampleid,sample_name,run_prefix,experimental_strategy,cgc_base_name,filename,analyte_amount,analyte_A260A280Ratio,aliquot_concentration,cgc_id,...,data_submitting_center_label,tissue_source_site_label,country_of_sample_procurement,portion_is_ffpe,pathologic_t_label,pathologic_n_label,histological_diagnosis_label,pathologic_stage_label,PlateCenter,PlateCenterFlag
0,13722.58cfa82fe4b0c9d6adf6b62c,58cfa82fe4b0c9d6adf6b62c,TCGA-50-5941-01A-11D-1751_111007_SN590_0110_C0...,WGS,TCGA-50-5941-01A-11D-1751_111007_SN590_0110_C0...,TCGA-50-5941-01A-11D-1751_111007_SN590_0110_C0...,237.4,1.9,0.16,58cfa82fe4b0c9d6adf6b62c,...,Harvard Medical School,University of Pittsburgh,United States,NO,T2a,N2,Lung Adenocarcinoma- Not Otherwise Specified (...,Stage IIIA,1751-02,True
1,13722.58cfa82fe4b0c9d6adf6b5e0,58cfa82fe4b0c9d6adf6b5e0,TCGA-50-5941-10A-01D-1751_111007_SN590_0110_C0...,WGS,TCGA-50-5941-10A-01D-1751_111007_SN590_0110_C0...,TCGA-50-5941-10A-01D-1751_111007_SN590_0110_C0...,30.7,1.9,0.16,58cfa82fe4b0c9d6adf6b5e0,...,Harvard Medical School,University of Pittsburgh,United States,NO,T2a,N2,Lung Adenocarcinoma- Not Otherwise Specified (...,Stage IIIA,1751-02,True
2,13722.58cfa82ee4b0c9d6adf6af8e,58cfa82ee4b0c9d6adf6af8e,TCGA-05-4405-10A-01D-1853_111204_SN208_0256_C0...,WGS,TCGA-05-4405-10A-01D-1853_111204_SN208_0256_C0...,TCGA-05-4405-10A-01D-1853_111204_SN208_0256_C0...,43.0,1.9,0.14,58cfa82ee4b0c9d6adf6af8e,...,Harvard Medical School,Indivumed,Germany,NO,T2,N0,Lung Adenocarcinoma Mixed Subtype,Stage IB,1853-02,True
3,13722.58cfa82ee4b0c9d6adf6af20,58cfa82ee4b0c9d6adf6af20,TCGA-05-4415-01A-22D-1853_111204_SN208_0256_C0...,WGS,TCGA-05-4415-01A-22D-1853_111204_SN208_0256_C0...,TCGA-05-4415-01A-22D-1853_111204_SN208_0256_C0...,143.7,1.9,0.14,58cfa82ee4b0c9d6adf6af20,...,Harvard Medical School,Indivumed,Germany,NO,T4,N2,Lung Adenocarcinoma Mixed Subtype,Stage IIIB,1853-02,True
4,13722.58cfa82fe4b0c9d6adf6b669,58cfa82fe4b0c9d6adf6b669,TCGA-44-6775-11A-01D-1853_111207_SN590_0112_D0...,WGS,TCGA-44-6775-11A-01D-1853_111207_SN590_0112_D0...,TCGA-44-6775-11A-01D-1853_111207_SN590_0112_D0...,16.7,1.9,0.14,58cfa82fe4b0c9d6adf6b669,...,Harvard Medical School,Christiana Healthcare,United States,NO,T2a,N0,Lung Adenocarcinoma- Not Otherwise Specified (...,Stage IB,1853-02,True

In [7]:
taxonomy = pd.read_csv("data/taxonomy_table_rep200.tsv",sep="\t",header=0)
taxonomy.head()

,genomeID,Domain,Phylum,Class,Order,Family,Genus,Species
0,G000001985,k__Eukaryota,p__Ascomycota,c__Eurotiomycetes,o__Eurotiales,f__Trichocomaceae,g__Talaromyces,s__Talaromyces marneffei
1,G000002415,k__Eukaryota,p__Apicomplexa,c__Aconoidasida,o__Haemosporida,f__Plasmodiidae,g__Plasmodium,s__Plasmodium vivax
2,G000002435,k__Eukaryota,p__Fornicata,c__,o__Diplomonadida,f__Hexamitidae,g__Giardia,s__Giardia intestinalis
3,G000002495,k__Eukaryota,p__Ascomycota,c__Sordariomycetes,o__Magnaporthales,f__Pyriculariaceae,g__Pyricularia,s__Pyricularia oryzae
4,G000002515,k__Eukaryota,p__Ascomycota,c__Saccharomycetes,o__Saccharomycetales,f__Saccharomycetaceae,g__Kluyveromyces,s__Kluyveromyces lactis

In [8]:

metadata_ml = fungi_metadata[['sampleid','disease_type','sample_type']]
metadata_ml_tumor = metadata_ml[metadata_ml['sample_type']=='Primary Tumor']
metadata_ml_tumor

,sampleid,disease_type,sample_type
0,13722.58cfa82fe4b0c9d6adf6b62c,Lung Adenocarcinoma,Primary Tumor
3,13722.58cfa82ee4b0c9d6adf6af20,Lung Adenocarcinoma,Primary Tumor
9,13722.58cfa82fe4b0c9d6adf6b6d8,Lung Adenocarcinoma,Primary Tumor
10,13722.58cfa82fe4b0c9d6adf6b648,Lung Adenocarcinoma,Primary Tumor
12,13722.58cfa82fe4b0c9d6adf6b60d,Lung Adenocarcinoma,Primary Tumor
...,...,...,...
1968,13722.58cfa831e4b0c9d6adf6ca0c,Bladder Urothelial Carcinoma,Primary Tumor
1969,13722.58cfa831e4b0c9d6adf6ca56,Brain Lower Grade Glioma,Primary Tumor
1975,13722.58cfa831e4b0c9d6adf6cc92,Prostate Adenocarcinoma,Primary Tumor
1981,13722.58cfa832e4b0c9d6adf6ceda,Prostate Adenocarcinoma,Primary Tumor
1982,13722.58cfa832e4b0c9d6adf6cedd,Prostate Adenocarcinoma,Primary Tumor

In [9]:
disease_type_counts = metadata_ml_tumor['disease_type'].value_counts()
disease_type_counts.index

Index(['Lung Adenocarcinoma', 'Stomach Adenocarcinoma',
       'Prostate Adenocarcinoma', 'Uterine Corpus Endometrial Carcinoma',
       'Head and Neck Squamous Cell Carcinoma', 'Colon Adenocarcinoma',
       'Thyroid Carcinoma', 'Brain Lower Grade Glioma',
       'Bladder Urothelial Carcinoma', 'Rectum Adenocarcinoma',
       'Breast Invasive Carcinoma', 'Skin Cutaneous Melanoma',
       'Cervical Squamous Cell Carcinoma and Endocervical Adenocarcinoma'],
      dtype='object')

In [86]:
def organize_data_for_ml(dataset):
    for dt in disease_type_counts.index:
        temp_meta = metadata_ml_tumor
        temp_meta['predY'] = temp_meta['disease_type'].apply(lambda disease: disease if disease == dt else "OtherCancerType")
        predY_counts = temp_meta['predY'].value_counts() 
        if any(predY_counts < 20): continue
        
        minorityClassSize = predY_counts.min()
        majorityClassSize = predY_counts.max()
        
        minorityClassName = predY_counts.idxmin()
        majorityClassName = predY_counts.idxmax()
        
        trainX = pd.merge(left=dataset,right=temp_meta['sampleid'], on='sampleid',how='inner')
        trainY = temp_meta.set_index('sampleid')[['predY']]
    return trainX,trainY

In [87]:
trainX,trainY = organize_data_for_ml(fungi_high)

In [88]:
trainY

                                          predY
sampleid
13722.58cfa82fe4b0c9d6adf6b62c  OtherCancerType
13722.58cfa82ee4b0c9d6adf6af20  OtherCancerType
13722.58cfa82fe4b0c9d6adf6b6d8  OtherCancerType
13722.58cfa82fe4b0c9d6adf6b648  OtherCancerType
13722.58cfa82fe4b0c9d6adf6b60d  OtherCancerType
...                                         ...
13722.58cfa831e4b0c9d6adf6ca0c  OtherCancerType
13722.58cfa831e4b0c9d6adf6ca56  OtherCancerType
13722.58cfa831e4b0c9d6adf6cc92  OtherCancerType
13722.58cfa832e4b0c9d6adf6ceda  OtherCancerType
13722.58cfa832e4b0c9d6adf6cedd  OtherCancerType

[876 rows x 1 columns]

In [89]:
from qiime2.plugins.sample_classifier.pipelines import classify_samples

In [90]:
trainX

,sampleid,G000002515,G000002545,G000003855,G000006335,G000006445,G000026945,G000091025,G000146045,G000149425,...,G001298625,G001417885,G001642055,G001661405,G002079055,G002775015,G003290485,G004154835,G004353045,G900007375
0,13722.58cfa82fe4b0c9d6adf6b62c,0,0,2,0,0,0,0,0,0,...,0,0,0,0,0,0,2,0,4,0
1,13722.58cfa82ee4b0c9d6adf6af20,0,0,3,0,0,0,0,0,0,...,0,0,0,0,0,0,3,1,1,0
2,13722.58cfa82fe4b0c9d6adf6b6d8,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,2,0
3,13722.58cfa82fe4b0c9d6adf6b648,0,0,0,0,0,0,0,7,0,...,0,0,0,0,1,0,2,2,30,1
4,13722.58cfa82fe4b0c9d6adf6b60d,0,0,1,0,0,0,0,10,0,...,0,1,0,0,0,0,22,1,54,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
871,13722.58cfa831e4b0c9d6adf6ca0c,0,0,2,0,0,0,0,0,0,...,0,0,0,2,0,0,4,7,2,0
872,13722.58cfa831e4b0c9d6adf6ca56,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
873,13722.58cfa831e4b0c9d6adf6cc92,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,8,0,0,0
874,13722.58cfa832e4b0c9d6adf6ceda,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,2,0,0,0
875,13722.58cfa832e4b0c9d6adf6cedd,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [91]:
imported_artifact = qiime2.Artifact.import_data("FeatureTable[Frequency]", trainX.set_index('sampleid'))

In [93]:
trainY

                                          predY
sampleid
13722.58cfa82fe4b0c9d6adf6b62c  OtherCancerType
13722.58cfa82ee4b0c9d6adf6af20  OtherCancerType
13722.58cfa82fe4b0c9d6adf6b6d8  OtherCancerType
13722.58cfa82fe4b0c9d6adf6b648  OtherCancerType
13722.58cfa82fe4b0c9d6adf6b60d  OtherCancerType
...                                         ...
13722.58cfa831e4b0c9d6adf6ca0c  OtherCancerType
13722.58cfa831e4b0c9d6adf6ca56  OtherCancerType
13722.58cfa831e4b0c9d6adf6cc92  OtherCancerType
13722.58cfa832e4b0c9d6adf6ceda  OtherCancerType
13722.58cfa832e4b0c9d6adf6cedd  OtherCancerType

[876 rows x 1 columns]

In [96]:
metadata = qiime2.Metadata(trainY)

In [103]:
metadata.to_dataframe()

                                          predY
sampleid
13722.58cfa82fe4b0c9d6adf6b62c  OtherCancerType
13722.58cfa82ee4b0c9d6adf6af20  OtherCancerType
13722.58cfa82fe4b0c9d6adf6b6d8  OtherCancerType
13722.58cfa82fe4b0c9d6adf6b648  OtherCancerType
13722.58cfa82fe4b0c9d6adf6b60d  OtherCancerType
...                                         ...
13722.58cfa831e4b0c9d6adf6ca0c  OtherCancerType
13722.58cfa831e4b0c9d6adf6ca56  OtherCancerType
13722.58cfa831e4b0c9d6adf6cc92  OtherCancerType
13722.58cfa832e4b0c9d6adf6ceda  OtherCancerType
13722.58cfa832e4b0c9d6adf6cedd  OtherCancerType

[876 rows x 1 columns]

In [135]:
results = classify_samples(table=imported_artifact,metadata=metadata.get_column('predY'),cv = 10, estimator='GradientBoostingClassifier',n_estimators = 150,parameter_tuning=False,random_state=42,test_size=.1)

In [136]:
results

Results (name = value)
-------------------------------------------------------------------------------------------------------------
sample_estimator   = <artifact: SampleEstimator[Classifier] uuid: b109b901-e25d-4281-a640-265c7708a4bf>
feature_importance = <artifact: FeatureData[Importance] uuid: 301ba419-c3c4-458e-abce-fee28d162510>
predictions        = <artifact: SampleData[ClassifierPredictions] uuid: 51e98f9f-3092-4386-a4bb-52dd489ba66f>
model_summary      = <visualization: Visualization uuid: 6228d230-4295-4ba5-b959-8203da9f2cfc>
accuracy_results   = <visualization: Visualization uuid: 52117a1a-7f86-4d2b-83d9-e92820e04370>
probabilities      = <artifact: SampleData[Probabilities] uuid: 606ee0c9-5405-4b25-8f99-2957014c2e8f>
heatmap            = <visualization: Visualization uuid: 81079829-2d26-44b4-adaf-3c4a64a198bf>
training_targets   = <artifact: SampleData[TrueTargets] uuid: 666488c7-591e-4d68-9618-413cb9a33ac7>
test_targets       = <artifact: SampleData[TrueTargets] uuid: 3625e4c3-2b3f-4239-85cb-1a8149653cf3>

In [137]:
results.heatmap.save('pic')

'pic.qzv'

{n.trees=150, interaction.depth=3, shrinkage=0.1, n.minobsinnode=1